#!/bin/sh
#
# Licensed Materials - Property of IBM
#
# 5724O4800
#
# (C) Copyright IBM Corp. 2003, 2009. All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication
# or disclosure restricted by GSA ADP Schedule Contract
# with IBM Corp.
#
# nco_cftp - perfrom file transfer over the ITM file conduit
#
# --
#######################################

#######################################
# MAIN
#######################################


NCCI_JRE=jre_1.5.6/jre

#######################################
# Find nco_common
NCO_COMMON=`dirname $0`/../bin/nco_common

# Check for nco_common, and load if found
if [ ! -f "$NCO_COMMON" ]; then
        echo "Cannot find nco_common" 1>&2
        exit 1
fi
. $NCO_COMMON



if [ "$NCHOME" = ""  ]
then
	
	echo Cannot find your NCHOME environment
	exit 1
	
fi



# redefine OMNIHOME to NCHOME/omnibus
OMNIHOME="$NCHOME/omnibus"


if [ "$CANDLE_CJ_HOME" = ""  ]
then
	
	echo Cannot find your CANDLE_CJ_HOME environment
	exit 1
	
fi


#
# Locate JRE
#
if [ "$NCO_JRE" = "" -o ! -x "$NCO_JRE/bin/java" ]
then
	if [ -x "$NCHOME/platform/$ARCH/$NCCI_JRE/bin/java" ]
	then
		NCO_JRE="$NCHOME/platform/$ARCH/$NCCI_JRE"
	else
		echo Cannot find your Java environment
		echo $NCHOME/platform/$ARCH/$NCCI_JRE
		exit 1
	fi
fi


P_LNF="-Dswing.metalTheme=steel"


#
# Fix for JDK bug on AIX:
# ARCH Variable is set in nco_common
#
if [ $ARCH = "aix4" -o $ARCH = "aix5" ]; then
echo "Unsetting XPG_SUS_ENV" 1>&2
unset XPG_SUS_ENV
P_LNF=""
fi

#
# Set classpath to only include relevant jar files
#

if [ -z "${CLASSPATH}" ]; then
	export CLASSPATH
fi




CLASSPATH=${OMNIHOME}/java/jars/cftp.jar
CLASSPATH=${CLASSPATH}:${CANDLE_CJ_HOME}/cj/lib/cnp_vbjorball.jar
CLASSPATH=${CLASSPATH}:${CANDLE_CJ_HOME}/cj/lib/ae.jar
CLASSPATH=${CLASSPATH}:${CANDLE_CJ_HOME}/cj/lib/cnp.jar
CLASSPATH=${CLASSPATH}:${CANDLE_CJ_HOME}/cj/lib/icu4jm32.jar
CLASSPATH=${CLASSPATH}:${CANDLE_CJ_HOME}/cj/lib/kjrall.jar
CLASSPATH=${CLASSPATH}:${CANDLE_CJ_HOME}/cj/lib/terminal.jar
CLASSPATH=${CLASSPATH}:${CANDLE_CJ_HOME}/cj/lib/util.jar

#
# Convert env vars to java commandline properties
#

P_OMNIHOME="-Domni.home=${OMNIHOME}"
P_NCHOME="-Dnc.home=${NCHOME}"
P_CNDLHOME="-DCANDLE_HOME=${CANDLE_CJ_HOME}"
P_MEMORY="-Xms64m -Xmx512m"

#
# Start class with main entry
#
exec "${NCO_JRE}/bin/java" -classpath ${CLASSPATH} \
	${P_NCHOME} ${P_OMNIHOME} \
	${P_CNDLHOME} \
	${P_MEMORY} ${P_LNF} \
	com.ibm.cdb.integration.itm.ConduitFileTransferHelper "$@"

	
