#!/bin/sh 
#
# Licensed Materials - Property of IBM
#
# 5724O4800
#
# (C) Copyright IBM Corp. 1994, 2005. All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication
# or disclosure restricted by GSA ADP Schedule Contract
# with IBM Corp.
#
#
# New Server script -  Points user to nco_dbinit
#
# 5.50.48
#

#######################################

echo "nco_new_server is deprecated. Use nco_dbinit to initialize your ObjectServer."
echo "Type \$OMNIHOME/bin/nco_dbinit -help to see the options available."
