DELETE FROM O4SRV.TSITDESC WHERE SITNAME = "Event_Rate_TTCT_1W";
DELETE FROM O4SRV.TSITDESC WHERE SITNAME = "Event_Rate_TTWT_1W";
DELETE FROM O4SRV.TOBJACCL WHERE OBJNAME = "Event_Rate_TTCT_1W";
DELETE FROM O4SRV.TOBJACCL WHERE OBJNAME = "Event_Rate_TTWT_1W";
